- name: install packages
  become: true
  apt:
    name:
      - make
      - build-essential
      - libssl-dev
      - zlib1g-dev
      - libbz2-dev
      - libreadline-dev
      - libsqlite3-dev
      - wget
      - curl
      - llvm
      - libncursesw5-dev
      - xz-utils
      - tk-dev
      - libxml2-dev
      - libxmlsec1-dev
      - libffi-dev
      - liblzma-dev
    update_cache: yes
    cache_valid_time: 3600
  when:
    - ansible_facts.distribution == "Ubuntu"

- name: install packages
  shell: |
    echo "Not implemented yet!"
    exit 1
  when:
    - ansible_facts.distribution != "Ubuntu"

- name: install git
  become: true
  apt:
    name: git
    update_cache: yes
    cache_valid_time: 3600
  when:
    - ansible_facts.distribution == "Ubuntu"
- name: install pyenv
  git:
    repo: "https://github.com/pyenv/pyenv.git"
    dest: "~/.pyenv"
    force: yes
- name: optional
  command:
    chdir: "~/.pyenv"
    cmd: >
      src/configure
      &&
      make -C src

- name: setup bash
  # command:
  args:
    executable: /bin/bash
  shell:
    cmd: |

      setup_for_pyenv () {
      local config_file="$1"

      cat <<-'EOF' | tee --append "${config_file}"

      export PYENV_ROOT="$HOME/.pyenv"

      pyenv_bin_path="$PYENV_ROOT/bin"
      if [[ -d "${pyenv_bin_path}" ]]\
      && [[ -n "${PATH##*${pyenv_bin_path}}" ]]\
      && [[ -n "${PATH##*${pyenv_bin_path}:*}" ]]; then
          export PATH="${pyenv_bin_path}:$PATH"
      fi

      eval "$(pyenv init -)"

      EOF

      }

      setup_for_pyenv {{ item }}

  with_items:
    - ~/.bashrc
    # - ~/.bash_profile
    # - ~/.bash_login
    - ~/.zshrc
    # - ~/zprofile
    # - ~/zlogin

- name: install pyenv-virtualenv
  git:
    repo: "https://github.com/pyenv/pyenv-virtualenv.git"
    dest: "$HOME/.pyenv/plugins/pyenv-virtualenv"
    force: yes
- name: update shell config
  args:
    executable: /bin/bash
  shell:
    cmd: |
      echo 'eval "$(pyenv virtualenv-init -)"' >> {{ item }}
  with_items:
    - ~/.bashrc
    - ~/.zshrc
