- name: git clone rbenv
  git:
    repo: "https://github.com/rbenv/rbenv.git"
    dest: "~/.rbenv"
    force: yes
- name: make
  args:
    executable: /bin/bash
  shell:
    chdir: "~/.rbenv"
    cmd: >
      src/configure
      &&
      make -C src

- name: create plugin directory
  file:
    path: ~/.rbenv/plugins
    state: directory
    mode: "0755"
    recurse: yes
- name: git clone ruby-build
  git:
    repo: "https://github.com/rbenv/ruby-build.git"
    dest: "~/.rbenv/plugins/ruby-build"
    force: yes

- name: update shell config
  args:
    executable: /bin/bash
  shell:
    cmd: |
      echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.{{ item }}rc
      echo 'eval "$(rbenv init - {{ item }})"'    >> ~/.{{ item }}rc
  with_items:
    - bash
    - zsh
