---
# <https://go.dev/doc/install>

- name: copy script
  template:
    src: install_go.sh
    dest: /tmp/install_go.sh
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: '0755'
- name: download and install go
  shell:
    cmd: /tmp/install_go.sh {{ go_download_url }}
